#############################################################################
# Makefile for building: SpaceX
# Generated by qmake (2.01a) (Qt 4.2.1) on: Tue Nov 14 20:18:00 2006
# Project:  SpaceX.pro
# Template: app
# Command: /home/john/dev/qt421/bin/qmake -unix -o Makefile SpaceX.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
LEX           = flex
YACC          = yacc
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT  $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT  $(DEFINES)
LEXFLAGS      = 
YACCFLAGS     = -d
INCPATH       = -I../qt421/mkspecs/linux-g++ -I. -I../qt421/include/QtCore -I../qt421/include/QtCore -I../qt421/include/QtGui -I../qt421/include/QtGui -I../qt421/include -I. -I../qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/john/dev/qt421/lib
LIBS          = $(SUBLIBS)  -L/home/john/dev/qt421/lib -lQtGui -L/home/john/dev/qt-x11-opensource-src-4.2.1/lib -L/usr/X11R6/lib -lSM -lICE -lXi -lXrender -lXrandr -lXext -lX11 -lQtCore -lm -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/john/dev/qt421/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = MainApp.cpp \
		GameMainWindow.cpp \
		SpaceMap.cpp \
		Planet.cpp \
		Planet_Info.cpp \
		GameBoard.cpp \
		GameController.cpp \
		Player.cpp \
		StartDialog.cpp \
		Fleet.cpp moc_GameMainWindow.cpp \
		moc_SpaceMap.cpp \
		moc_Planet.cpp \
		moc_Planet_Info.cpp \
		moc_GameBoard.cpp \
		moc_GameController.cpp \
		moc_Player.cpp \
		moc_StartDialog.cpp
OBJECTS       = MainApp.o \
		GameMainWindow.o \
		SpaceMap.o \
		Planet.o \
		Planet_Info.o \
		GameBoard.o \
		GameController.o \
		Player.o \
		StartDialog.o \
		Fleet.o \
		moc_GameMainWindow.o \
		moc_SpaceMap.o \
		moc_Planet.o \
		moc_Planet_Info.o \
		moc_GameBoard.o \
		moc_GameController.o \
		moc_Player.o \
		moc_StartDialog.o
DIST          = ../qt421/mkspecs/common/unix.conf \
		../qt421/mkspecs/common/g++.conf \
		../qt421/mkspecs/common/linux.conf \
		../qt421/mkspecs/qconfig.pri \
		../qt421/mkspecs/features/qt_functions.prf \
		../qt421/mkspecs/features/qt_config.prf \
		../qt421/mkspecs/features/exclusive_builds.prf \
		../qt421/mkspecs/features/default_pre.prf \
		../qt421/mkspecs/features/debug.prf \
		../qt421/mkspecs/features/default_post.prf \
		../qt421/mkspecs/features/warn_on.prf \
		../qt421/mkspecs/features/qt.prf \
		../qt421/mkspecs/features/unix/thread.prf \
		../qt421/mkspecs/features/moc.prf \
		../qt421/mkspecs/features/resources.prf \
		../qt421/mkspecs/features/uic.prf \
		SpaceX.pro
QMAKE_TARGET  = SpaceX
DESTDIR       = 
TARGET        = SpaceX

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SpaceX.pro  ../qt421/mkspecs/linux-g++/qmake.conf ../qt421/mkspecs/common/unix.conf \
		../qt421/mkspecs/common/g++.conf \
		../qt421/mkspecs/common/linux.conf \
		../qt421/mkspecs/qconfig.pri \
		../qt421/mkspecs/features/qt_functions.prf \
		../qt421/mkspecs/features/qt_config.prf \
		../qt421/mkspecs/features/exclusive_builds.prf \
		../qt421/mkspecs/features/default_pre.prf \
		../qt421/mkspecs/features/debug.prf \
		../qt421/mkspecs/features/default_post.prf \
		../qt421/mkspecs/features/warn_on.prf \
		../qt421/mkspecs/features/qt.prf \
		../qt421/mkspecs/features/unix/thread.prf \
		../qt421/mkspecs/features/moc.prf \
		../qt421/mkspecs/features/resources.prf \
		../qt421/mkspecs/features/uic.prf \
		/home/john/dev/qt421/lib/libQtGui.prl \
		/home/john/dev/qt421/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile SpaceX.pro
../qt421/mkspecs/common/unix.conf:
../qt421/mkspecs/common/g++.conf:
../qt421/mkspecs/common/linux.conf:
../qt421/mkspecs/qconfig.pri:
../qt421/mkspecs/features/qt_functions.prf:
../qt421/mkspecs/features/qt_config.prf:
../qt421/mkspecs/features/exclusive_builds.prf:
../qt421/mkspecs/features/default_pre.prf:
../qt421/mkspecs/features/debug.prf:
../qt421/mkspecs/features/default_post.prf:
../qt421/mkspecs/features/warn_on.prf:
../qt421/mkspecs/features/qt.prf:
../qt421/mkspecs/features/unix/thread.prf:
../qt421/mkspecs/features/moc.prf:
../qt421/mkspecs/features/resources.prf:
../qt421/mkspecs/features/uic.prf:
/home/john/dev/qt421/lib/libQtGui.prl:
/home/john/dev/qt421/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile SpaceX.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/SpaceX1.0.0 || $(MKDIR) .tmp/SpaceX1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/SpaceX1.0.0/ && $(COPY_FILE) --parents GameMainWindow.h SpaceMap.h Planet.h Planet_Info.h GameBoard.h GameController.h Player.h StartDialog.h Fleet.h .tmp/SpaceX1.0.0/ && $(COPY_FILE) --parents MainApp.cpp GameMainWindow.cpp SpaceMap.cpp Planet.cpp Planet_Info.cpp GameBoard.cpp GameController.cpp Player.cpp StartDialog.cpp Fleet.cpp .tmp/SpaceX1.0.0/ && (cd `dirname .tmp/SpaceX1.0.0` && $(TAR) SpaceX1.0.0.tar SpaceX1.0.0 && $(COMPRESS) SpaceX1.0.0.tar) && $(MOVE) `dirname .tmp/SpaceX1.0.0`/SpaceX1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/SpaceX1.0.0


yaccclean:
lexclean:
clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


/home/john/dev/qt421/bin/moc:
	(cd $(QTDIR)/src/tools/moc && $(MAKE))

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_GameMainWindow.cpp moc_SpaceMap.cpp moc_Planet.cpp moc_Planet_Info.cpp moc_GameBoard.cpp moc_GameController.cpp moc_Player.cpp moc_StartDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_GameMainWindow.cpp moc_SpaceMap.cpp moc_Planet.cpp moc_Planet_Info.cpp moc_GameBoard.cpp moc_GameController.cpp moc_Player.cpp moc_StartDialog.cpp
moc_GameMainWindow.cpp: GameBoard.h \
		SpaceMap.h \
		Planet.h \
		Player.h \
		Planet_Info.h \
		GameController.h \
		StartDialog.h \
		GameMainWindow.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) GameMainWindow.h -o moc_GameMainWindow.cpp

moc_SpaceMap.cpp: Planet.h \
		Player.h \
		SpaceMap.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) SpaceMap.h -o moc_SpaceMap.cpp

moc_Planet.cpp: Player.h \
		Planet.h \
		Planet.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) Planet.h -o moc_Planet.cpp

moc_Planet_Info.cpp: Planet.h \
		Player.h \
		Planet_Info.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) Planet_Info.h -o moc_Planet_Info.cpp

moc_GameBoard.cpp: SpaceMap.h \
		Planet.h \
		Player.h \
		Planet_Info.h \
		GameBoard.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) GameBoard.h -o moc_GameBoard.cpp

moc_GameController.cpp: Planet.h \
		Player.h \
		GameController.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) GameController.h -o moc_GameController.cpp

moc_Player.cpp: Planet.h \
		Player.h \
		Player.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) Player.h -o moc_Player.cpp

moc_StartDialog.cpp: StartDialog.h \
		../qt421/bin/moc
	/home/john/dev/qt421/bin/moc $(DEFINES) $(INCPATH) StartDialog.h -o moc_StartDialog.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_image_collection_clean compiler_moc_source_clean compiler_uic_clean 

####### Compile

MainApp.o: MainApp.cpp GameMainWindow.h \
		GameBoard.h \
		SpaceMap.h \
		Planet.h \
		Player.h \
		Planet_Info.h \
		GameController.h \
		StartDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainApp.o MainApp.cpp

GameMainWindow.o: GameMainWindow.cpp GameMainWindow.h \
		GameBoard.h \
		SpaceMap.h \
		Planet.h \
		Player.h \
		Planet_Info.h \
		GameController.h \
		StartDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameMainWindow.o GameMainWindow.cpp

SpaceMap.o: SpaceMap.cpp SpaceMap.h \
		Planet.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SpaceMap.o SpaceMap.cpp

Planet.o: Planet.cpp Planet.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Planet.o Planet.cpp

Planet_Info.o: Planet_Info.cpp Planet_Info.h \
		Planet.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Planet_Info.o Planet_Info.cpp

GameBoard.o: GameBoard.cpp GameBoard.h \
		SpaceMap.h \
		Planet.h \
		Player.h \
		Planet_Info.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameBoard.o GameBoard.cpp

GameController.o: GameController.cpp GameController.h \
		Planet.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameController.o GameController.cpp

Player.o: Player.cpp Player.h \
		Planet.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Player.o Player.cpp

StartDialog.o: StartDialog.cpp StartDialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o StartDialog.o StartDialog.cpp

Fleet.o: Fleet.cpp Fleet.h \
		Planet.h \
		Player.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Fleet.o Fleet.cpp

moc_GameMainWindow.o: moc_GameMainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameMainWindow.o moc_GameMainWindow.cpp

moc_SpaceMap.o: moc_SpaceMap.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SpaceMap.o moc_SpaceMap.cpp

moc_Planet.o: moc_Planet.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Planet.o moc_Planet.cpp

moc_Planet_Info.o: moc_Planet_Info.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Planet_Info.o moc_Planet_Info.cpp

moc_GameBoard.o: moc_GameBoard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameBoard.o moc_GameBoard.cpp

moc_GameController.o: moc_GameController.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_GameController.o moc_GameController.cpp

moc_Player.o: moc_Player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_Player.o moc_Player.cpp

moc_StartDialog.o: moc_StartDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_StartDialog.o moc_StartDialog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

